<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MACH-PC176" failures="0" tests="6" name="com.JenkinUse.SampleProject.NewTest" time="10.225" errors="1" timestamp="2024-04-05T16:03:26 IST" skipped="5">
  <testcase classname="com.JenkinUse.SampleProject.NewTest" name="HomePage" time="10.225">
    <error message="Invalid file path" type="java.io.IOException">
      <![CDATA[java.io.IOException: Invalid file path
at java.base/java.io.File.getCanonicalPath(File.java:624)
at org.apache.commons.io.FileUtils.requireCanonicalPathsNotEquals(FileUtils.java:2601)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:842)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
at com.JenkinUse.SampleProject.Utility.CaptureScreenshot(Utility.java:118)
at com.JenkinUse.SampleProject.Utility.VerifPageURL(Utility.java:67)
at com.JenkinUse.SampleProject.Utility.WebPage(Utility.java:53)
at com.JenkinUse.SampleProject.NewTest.HomePage(NewTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- HomePage -->
  <system-out/>
  <testcase classname="com.JenkinUse.SampleProject.NewTest" name="PricingPage">
    <skipped/>
  </testcase> <!-- PricingPage -->
  <system-out/>
  <testcase classname="com.JenkinUse.SampleProject.NewTest" name="WhyUsPage">
    <skipped/>
  </testcase> <!-- WhyUsPage -->
  <system-out/>
  <testcase classname="com.JenkinUse.SampleProject.NewTest" name="ContentHubPage">
    <skipped/>
  </testcase> <!-- ContentHubPage -->
  <system-out/>
  <testcase classname="com.JenkinUse.SampleProject.NewTest" name="MachintelContent">
    <skipped/>
  </testcase> <!-- MachintelContent -->
  <system-out/>
  <testcase classname="com.JenkinUse.SampleProject.NewTest" name="OurDataPage">
    <skipped/>
  </testcase> <!-- OurDataPage -->
  <system-out/>
</testsuite> <!-- com.JenkinUse.SampleProject.NewTest -->
